CartPole-v1:
  discount_factor: 0.99

  actor_lr: 0.0003
  critic_lr: 0.0007

  replay_memory_size: 50000
  batch_size: 256
  tau: 0.01

  alpha: 0.0
  automatic_entropy_tuning: false

  epsilon_start: 1.0
  epsilon_decay: 0.995
  epsilon_min: 0.0

  episodes: 700
  convergence_threshold: 475.0
  convergence_window: 100

Acrobot-v1:
  discount_factor: 0.99

  actor_lr: 0.0005
  critic_lr: 0.001

  replay_memory_size: 30000
  batch_size: 256
  tau: 0.005

  alpha: 0.2
  automatic_entropy_tuning: false

  epsilon_start: 1.0
  epsilon_decay: 0.997
  epsilon_min: 0.05

  episodes: 500
  convergence_threshold: -100.0
  convergence_window: 100

MountainCar-v0:
  discount_factor: 0.99

  actor_lr: 0.0007
  critic_lr: 0.001

  replay_memory_size: 100000
  batch_size: 256
  tau: 0.005

  alpha: 0.0
  automatic_entropy_tuning: false

  epsilon_start: 1.0
  epsilon_decay: 0.999
  epsilon_min: 0.05

  episodes: 2000
  convergence_threshold: -110.0
  convergence_window: 100

Pendulum-v1:
  discount_factor: 0.97

  actor_lr: 0.00025
  critic_lr: 0.0005

  replay_memory_size: 100000
  batch_size: 256
  tau: 0.005

  alpha: 0.005
  automatic_entropy_tuning: false

  episodes: 1000
  convergence_threshold: -200.0
  convergence_window: 100
